CREATE DATABASE customer_behavior;
USE customer_behavior;


--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY gender;

--Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >
      (SELECT AVG(purchase_amount_usd)
       FROM customer);



Q3. Which are the top 5 products with the highest average review rating?
SELECT
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

--Q4. Compare the average purchase amounts between Standard and Express shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount_usd), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;



--Q5. Do subscribed customers spend more? Compare average spend and total revenue.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount_usd), 2) AS average_spend,
       ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on previous purchases.
WITH customer_segment AS (
    SELECT customer_id,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_type
    FROM customer
)
SELECT customer_type,
       COUNT(*) AS number_of_customers
FROM customer_segment
GROUP BY customer_type;


--Q8. What are the top 3 most purchased products within each category?
WITH product_ranking AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS product_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT category,
       item_purchased,
       total_orders
FROM product_ranking
WHERE product_rank <= 3;


--Q9. Are repeat buyers (more than 5 previous purchases) likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. Revenue contribution of each age group
SELECT age_group,
       SUM(purchase_amount_usd) AS total_revenue
FROM (
    SELECT
        CASE
            WHEN age BETWEEN 18 AND 30 THEN 'Young Adult'
            WHEN age BETWEEN 31 AND 45 THEN 'Adult'
            WHEN age BETWEEN 46 AND 60 THEN 'Middle-aged'
            ELSE 'Senior'
        END AS age_group,
        purchase_amount_usd
    FROM customer
) AS age_data
GROUP BY age_group
ORDER BY total_revenue DESC;



SELECT age_group,
       SUM(purchase_amount_usd) AS total_revenue
FROM (
    SELECT
        CASE
            WHEN age BETWEEN 18 AND 30 THEN 'Young Adult'
            WHEN age BETWEEN 31 AND 45 THEN 'Adult'
            WHEN age BETWEEN 46 AND 60 THEN 'Middle-aged'
            ELSE 'Senior'
        END AS age_group,
        purchase_amount_usd
    FROM customer
) AS age_data
GROUP BY age_group
ORDER BY total_revenue DESC;


